[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "resnet-implementation"
version = "0.1.0"
dependencies = [
  "numpy>=2.2.5",
  "torch>=2.6.0",
  "matplotlib>=3.10.1",
  "tqdm"
]
